#include<iostream.h>
#include<iomanip.h>
#include<conio.h>
#include<stdio.h>
#include<stdlib.h>

void main()
{
	int n,p;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
    cout<<"                        MCQ  (MULTIPLE CHOICE QUESTIONS)"<<endl;
	cout<<" "<<endl;
    cout<<"                       User Name : Mohammed Usman E Gani"<<endl;
    cout<<"                       Password  : ";
	cin>>p;
	system("ClS");
	if(p==583102)
	{
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
    cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<"                                 * WEL COME *"<<endl;
		cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<"                                               Press ENTER to  Continue ..."<<endl;
	getch();
	system("ClS");
		cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<"********************************************************************************"<<endl;
	cout<<"                         *** SOFT WARE DEVELOPING MANAGER ***  "<<endl;
    cout<<" "<<endl;
	cout<<"                               MOHAMMED USMAN -E- GANI "<<endl;
	cout<<"********************************************************************************"<<endl;

	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<"                                               Press ENTER to  Continue ..."<<endl;
	getch();
	system("ClS");
	cout<<" "<<endl;
	cout<<"                          *** Multiple choice questions ***"<<endl;
	cout<<" "<<endl;
	cout<<" TOPIC : C++ basics"<<endl;
    cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" 1.The Programming language among the following is:"<<endl;
    cout<<" "<<endl;
	cout<<" 1. JAVA"<<endl;
	cout<<" 2. Kannada"<<endl;
	cout<<" 3. Both 1 & 4"<<endl;
	cout<<" 4. C++"<<endl;
	cout<<" "<<endl;
	cout<<" Enter the correct option:";
	cout<<" ";
	cin>>n;
	if(n==3)

		cout<<" CORRECT"<<endl;
	else
		cout<<" WRONG ! ! !"<<endl;
	    cout<<"   "<<endl;
		getch();
	system("ClS");
	
 cout<<" "<<endl;
	cout<<" "<<endl;
	
	cout<<" 2.Which of the following is web Designing programming language:"<<endl;
    cout<<" "<<endl;
	cout<<" 1. HTML"<<endl;
	cout<<" 2. C++"<<endl;
	cout<<" 3. C--"<<endl;
	cout<<" 4. SQL"<<endl;
	cout<<" "<<endl;
	cout<<" Enter the correct option:";
	cout<<" ";
	cin>>n;
	if(n==1)

		cout<<" CORRECT"<<endl;
	else
		cout<<" WRONG ! ! !"<<endl;
	    cout<<"   "<<endl;
	
getch();
	system("ClS");
		 cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" 3.What is #include<iostream.h>:"<<endl;
    cout<<" "<<endl;
	cout<<" 1. Reader file"<<endl;
	cout<<" 2. Source file"<<endl;
	cout<<" 3. Header file"<<endl;
	cout<<" 4. None"<<endl;
	cout<<" "<<endl;
	cout<<" Enter the correct option:";
	cout<<" ";
	cin>>n;
	if(n==3)

		cout<<" CORRECT"<<endl;
	else
		cout<<" WRONG ! ! !"<<endl;
	    cout<<"   "<<endl;
	

getch();
	system("ClS");
	 cout<<" "<<endl;
	cout<<" "<<endl;
			
	cout<<" 4.Why is *clrscr* used in program:"<<endl;
    cout<<" "<<endl;
	cout<<" 1. To Display"<<endl;
	cout<<" 2. To clearing a screen"<<endl;
	cout<<" 3. To take input"<<endl;
	cout<<" 4. To make program correct"<<endl;
	cout<<" "<<endl;
	cout<<" Enter the correct option:";
	cout<<" ";
	cin>>n;
	if(n==2)

		cout<<" CORRECT"<<endl;
	else
		cout<<" WRONG ! ! !"<<endl;
	    cout<<"   "<<endl;
	

getch();
	system("ClS");
		 cout<<" "<<endl;
	cout<<" "<<endl;		
	cout<<" 5.*getch()* comes under which header file:"<<endl;
    cout<<" "<<endl;
	cout<<" 1. #include<iostream.h>"<<endl;
	cout<<" 2. #include<conio.h>"<<endl;
	cout<<" 3. #include<iomanip.h>"<<endl;
	cout<<" 4. #include<fstream.h>"<<endl;
	cout<<" "<<endl;
	cout<<" Enter the correct option:";
	cout<<" ";
	cin>>n;
	if(n==2)

		cout<<" CORRECT"<<endl;
	else
		cout<<" WRONG ! ! !"<<endl;
	    cout<<"   "<<endl;
	


					
    getch();
	system("ClS");
	 cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" 6.class must be ended with:"<<endl;
    cout<<" "<<endl;
	cout<<" 1. :"<<endl;
	cout<<" 2. ;"<<endl;
	cout<<" 3. +"<<endl;
	cout<<" 4. ="<<endl;
	cout<<" "<<endl;
	cout<<" Enter the correct option:";
	cout<<" ";
	cin>>n;
	if(n==2)

		cout<<" CORRECT"<<endl;
	else
		cout<<" WRONG ! ! !"<<endl;
	    cout<<"   "<<endl;
	

getch();
	system("ClS");
				 cout<<" "<<endl;
	cout<<" "<<endl;		
	cout<<" 7.int holds which type of data :"<<endl;
    cout<<" "<<endl;
	cout<<" 1. Integer"<<endl;
	cout<<" 2. Float"<<endl;
	cout<<" 3. Charachter"<<endl;
	cout<<" 4. NIL"<<endl;
	cout<<" "<<endl;
	cout<<" Enter the correct option:";
	cout<<" ";
	cin>>n;
	if(n==1)

		cout<<" CORRECT"<<endl;
	else
		cout<<" WRONG ! ! !"<<endl;
	    cout<<"   "<<endl;
	

getch();
	system("ClS");
		 cout<<" "<<endl;
	cout<<" "<<endl;					
	cout<<" 8.<iomanip.h>..............:"<<endl;
    cout<<" "<<endl;
	cout<<" 1. Input & output"<<endl;
	cout<<" 2. Input-output motors"<<endl;
	cout<<" 3. Input-output manipulators"<<endl;
	cout<<" 4. Graphics"<<endl;
	cout<<" "<<endl;
	cout<<" Enter the correct option:";
	cout<<" ";
	cin>>n;
	if(n==3)

		cout<<" CORRECT"<<endl;
	else
		cout<<" WRONG ! ! !"<<endl;
	    cout<<"   "<<endl;
	

getch();
	system("ClS");
	 cout<<" "<<endl;
	cout<<" "<<endl;							
	cout<<" 9.i++ means ...........:"<<endl;
    cout<<" "<<endl;
	cout<<" 1. incrementation in a"<<endl;
	cout<<" 2. incrementation in b"<<endl;
	cout<<" 3. incrementation in c"<<endl;
	cout<<" 4. incrementation in i"<<endl;
	cout<<" "<<endl;
	cout<<" Enter the correct option:";
	cout<<" ";
	cin>>n;
	if(n==4)

		cout<<" CORRECT"<<endl;
	else
		cout<<" WRONG ! ! !"<<endl;
	    cout<<"   "<<endl;
	


				getch();
	system("ClS");
	 cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" 10.Campiler is ...........:"<<endl;
    cout<<" "<<endl;
	cout<<" 1. Hard ware"<<endl;
	cout<<" 2. system Soft ware"<<endl;
	cout<<" 3. Tupper ware"<<endl;
	cout<<" 4. OS"<<endl;
	cout<<" "<<endl;
	cout<<" Enter the correct option:";
	cout<<" ";
	cin>>n;
	if(n==2)

		cout<<" CORRECT"<<endl;
	else
		cout<<" WRONG ! ! !"<<endl;
	    cout<<"   "<<endl;
	
	getch();
	system("ClS");
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;

		cout<<"********************************************************************************"<<endl;
		cout<<"                             ! ! ! THANKYOU ! ! !"<<endl;
		cout<<" "<<endl;
		cout<<"                       DEVELOPED BY MOHAMMED USMAN -E- GANI"<<endl;
		cout<<"********************************************************************************"<<endl;
		cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
	cout<<" "<<endl;
		cout<<"                                               Press ENTER to  EXIT ..."<<endl;
		


}

	else
	{
  		cout<<" "<<endl;
    	cout<<" "<<endl;
    	cout<<" "<<endl;
    	cout<<" "<<endl;
    	cout<<" "<<endl;
    	cout<<" "<<endl;
    	cout<<" "<<endl;
	    cout<<" "<<endl;
    	cout<<" "<<endl;
		cout<<"   "<<endl;
	    cout<<"   "<<endl;
		cout<<"                             !!! WRONG PASSWORD !!!"<<endl;
		cout<<"   "<<endl;
	    cout<<"   "<<endl;
		cout<<"                            !!! PLEASE TRY AGAIN !!!"<<endl;
	}
		




	



	getch();
}


